### ISSUE TITLE
Бот - премьеры недели.

### ISSUE THREAD

**Issue by evro23x** [evro23x/kino-domino#47]

**Comment by Askanio234** [comment]
Сделать 3 кнопкой? В плане: 

- Порекомендуй фильм

- Найди сеансы

- Покажи что нового на этой неделе

**Comment by evro23x** [comment]
Мне хотелось бы посмотреть какие новые фильмы вышли(или выйдут) на этой неделе, можно ссылку еще на трейлер скидывать и описание фильма.
По диалогу, думаю нужно по сценариям разделить, у нас возможно два сценария: 

- посмотреть кино дома 
- посмотреть кино в кинотеатре.

Далее, при выборе "в кинотеатре" лучше делить на поиск: 

- по кт 
- по фильму
- премьеры

Но это не точно, обсуждаемо.

**Comment by evro23x** [comment]
Готово, будет добавлено с релизом в среду.
