### ISSUE TITLE
Бот - формат вывода расписания

### ISSUE THREAD

**Issue by evro23x** [evro23x/kino-domino#49]

**Comment by evro23x** [comment]
Формат вывода расписания:

Зверопой

2017-03-02(четверг)
Формат - 2D
Сеанс: 13:25, цены: 350-500
Формат - 3D
Сеанс: 17:35, цены: 500-650
Сеанс: 19:30, цены: 500-650
Сеанс: 21:50, цены: 500-650

2017-03-03(пятница)
Формат -  IMAX 3D
Сеанс: 13:25, цены: 1350-1500
Сеанс: 17:35, цены: 1500-1650

**Comment by Askanio234** [comment]
Надо наверное название к/т упоминуть где-нить!

**Comment by evro23x** [comment]
Очень круто получилось!!
@Askanio234 Может лучше отделять вывод фильмов в разном формате?
Нужно поправить еще, чтобы день недели выдавался на русском.

**Comment by Askanio234** [comment]
День недели будет на том языке, на котором locale сервера настроена, наверное имеет смысл на сервере поставить ru_Ru локаль, насчет формата ухх надо подумать, итерировать и собирать в отдельную структуру данных надо, это может замедлить работу, наверное.

**Comment by evro23x** [comment]
Доработки:
- День недели выводить на русском языке
- Разделять фильмы по формату воспроизведения
- Переводить цену из флоата в инт(или отрезать точку)
- Не отображать цену при неизвестной стоимости билета
